services:
  node_a:
    image: rtix-dev
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /rtix/examples/python_ping_pong/node_a
    volumes:
      - ../..:/rtix
      - /tmp:/tmp
    ipc: host
    command: python3 run_node_a.py
  node_b:
    image: rtix-dev
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /rtix/examples/python_ping_pong/node_b
    volumes:
      - ../..:/rtix
      - /tmp:/tmp
    ipc: host
    command: python3 run_node_b.py
